'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import {
  EmptyState,
  FleetSetupPanel,
  OwnerShell,
  WorkspaceError,
  WorkspaceLoading,
  useOwnerWorkspaceData,
} from '../_components/owner-shared';
import { getDummyReportData } from './report-dummy-data';

/* ── Constants ── */

const DATE_FILTERS = [
  { value: 'this_week', label: 'This Week' },
  { value: 'last_week', label: 'Last Week' },
  { value: 'this_month', label: 'This Month' },
  { value: 'last_month', label: 'Last Month' },
];

/* ── Color tokens (single source of truth) ── */

const C = {
  navy: '#0A1628',
  orange: '#F97316',
  white: '#FFFFFF',
  offWhite: '#F8F9FA',
  muted: '#6B7280',
  border: '#E5E7EB',
  borderLight: '#F3F4F6',
};

/* ── Helpers ── */

function scoreLabel(score) {
  if (score >= 85) return 'Excellent';
  if (score >= 70) return 'Good';
  if (score >= 50) return 'Average';
  return 'High Risk';
}

function trendArrow(trend) {
  if (trend > 0) return { icon: '\u2191', color: C.navy, label: `+${trend}` };
  if (trend < 0) return { icon: '\u2193', color: C.orange, label: `${trend}` };
  return { icon: '\u2192', color: C.muted, label: '0' };
}

function buildWhatsAppMessage(summary, dateFilter) {
  const period = DATE_FILTERS.find((f) => f.value === dateFilter)?.label || 'This Week';
  return encodeURIComponent(
    `Fleet Report - ${period}\n\n` +
    `Fleet SAFAR Score: ${summary.safarScore}/100\n` +
    `Total Trips: ${summary.totalTrips}\n` +
    `High Risk Events: ${summary.highRiskEvents}\n` +
    `Active Drivers: ${summary.activeDrivers}/${summary.totalDrivers}\n\n` +
    `View full report: safar-admin.vercel.app/owner/reports\n\n` +
    `-- Generated by SAFAR`
  );
}

/* ── Shared inline-style helpers ── */

const sectionHeadingStyle = {
  fontSize: '11px',
  fontWeight: 500,
  textTransform: 'uppercase',
  letterSpacing: '0.08em',
  color: C.navy,
};

/* ── Section 1: Top Bar ── */

function TopBar({ dateFilter, setDateFilter, summary }) {
  return (
    <div style={{ border: `1px solid ${C.border}`, borderRadius: 12, background: C.white, padding: 24 }}>
      <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <p style={{ ...sectionHeadingStyle, color: C.orange }}>Fleet Reports</p>
          <h1 style={{ marginTop: 12, fontSize: '2rem', fontWeight: 500, letterSpacing: '-0.02em', color: C.navy }}>
            Fleet Performance Report
          </h1>
          <p style={{ marginTop: 12, maxWidth: '40rem', fontSize: '0.875rem', lineHeight: 1.7, color: C.muted }}>
            Review driver safety scores, trip stats, risk events, and weekly trends for your fleet.
          </p>
        </div>

        <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
          {/* Date filter pills */}
          <div style={{ display: 'inline-flex', flexWrap: 'wrap', borderRadius: 8, border: `1px solid ${C.border}`, background: C.offWhite, padding: 4 }}>
            {DATE_FILTERS.map((filter) => (
              <button
                key={filter.value}
                onClick={() => setDateFilter(filter.value)}
                style={{
                  borderRadius: 6,
                  padding: '8px 12px',
                  fontSize: '12px',
                  fontWeight: 500,
                  border: 'none',
                  cursor: 'pointer',
                  transition: 'all 0.15s',
                  background: filter.value === dateFilter ? C.navy : 'transparent',
                  color: filter.value === dateFilter ? C.white : C.muted,
                }}
              >
                {filter.label}
              </button>
            ))}
          </div>

          <div className="flex gap-2">
            {/* Download PDF - disabled */}
            <button
              disabled
              title="Coming soon"
              style={{
                display: 'inline-flex', alignItems: 'center', gap: 8,
                borderRadius: 8, border: `1px solid ${C.border}`, background: C.white,
                padding: '10px 16px', fontSize: '14px', fontWeight: 500,
                color: '#D1D5DB', cursor: 'not-allowed',
              }}
            >
              <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
              PDF
            </button>

            {/* WhatsApp Share */}
            <a
              href={`https://wa.me/?text=${buildWhatsAppMessage(summary, dateFilter)}`}
              target="_blank"
              rel="noopener noreferrer"
              style={{
                display: 'inline-flex', alignItems: 'center', gap: 8,
                borderRadius: 8, background: C.orange, color: C.white,
                padding: '10px 16px', fontSize: '14px', fontWeight: 500,
                textDecoration: 'none', transition: 'opacity 0.15s',
              }}
            >
              <svg className="h-4 w-4" fill="currentColor" viewBox="0 0 24 24"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" /></svg>
              Share
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ── Section 2: Fleet Summary Cards ── */

function SummaryCards({ summary }) {
  const trend = trendArrow(summary.scoreTrend);

  const cardStyle = {
    borderRadius: 12,
    border: `1px solid ${C.border}`,
    background: C.white,
    padding: 20,
  };

  return (
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      {/* SAFAR Score — primary KPI, uses orange */}
      <div style={cardStyle}>
        <p style={{ fontSize: '11px', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.08em', color: C.muted }}>
          Fleet SAFAR Score
        </p>
        <p style={{ marginTop: 12, fontSize: '2.25rem', fontWeight: 500, letterSpacing: '-0.02em', color: C.orange }}>
          {summary.safarScore}
        </p>
        <p style={{ marginTop: 8, fontSize: '13px', fontWeight: 400, color: trend.color }}>
          {trend.label} {trend.icon} from last week
        </p>
      </div>

      {/* Total Trips */}
      <div style={cardStyle}>
        <p style={{ fontSize: '11px', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.08em', color: C.muted }}>
          Total Trips
        </p>
        <p style={{ marginTop: 12, fontSize: '2.25rem', fontWeight: 500, letterSpacing: '-0.02em', color: C.navy }}>
          {summary.totalTrips}
        </p>
        <p style={{ marginTop: 8, fontSize: '13px', fontWeight: 400, color: C.muted }}>
          Trips this period
        </p>
      </div>

      {/* High Risk Events */}
      <div style={cardStyle}>
        <p style={{ fontSize: '11px', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.08em', color: C.muted }}>
          High Risk Events
        </p>
        <p style={{ marginTop: 12, fontSize: '2.25rem', fontWeight: 500, letterSpacing: '-0.02em', color: C.navy }}>
          {summary.highRiskEvents}
        </p>
        <p style={{ marginTop: 8, fontSize: '13px', fontWeight: 400, color: C.muted }}>
          Braking + Speeding + Swerving
        </p>
      </div>

      {/* Active Drivers */}
      <div style={cardStyle}>
        <p style={{ fontSize: '11px', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.08em', color: C.muted }}>
          Active Drivers
        </p>
        <p style={{ marginTop: 12, fontSize: '2.25rem', fontWeight: 500, letterSpacing: '-0.02em', color: C.navy }}>
          {summary.activeDrivers}
        </p>
        <p style={{ marginTop: 8, fontSize: '13px', fontWeight: 400, color: C.muted }}>
          of {summary.totalDrivers} total drivers
        </p>
      </div>
    </div>
  );
}

/* ── Section 3: Top Performers ── */

function TopPerformers({ drivers }) {
  const top3 = [...drivers].sort((a, b) => b.safetyScore - a.safetyScore).slice(0, 3);

  return (
    <div style={{ borderRadius: 12, border: `1px solid ${C.border}`, background: C.white }}>
      <div style={{ borderBottom: `1px solid ${C.border}`, padding: '20px 24px' }}>
        <p style={sectionHeadingStyle}>Top Performers This Week</p>
      </div>
      <div style={{ padding: '12px 16px' }}>
        {top3.map((driver, index) => {
          const trend = trendArrow(driver.scoreTrend);
          return (
            <div
              key={driver.id}
              style={{
                display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16,
                padding: '16px 8px',
                borderBottom: index < top3.length - 1 ? `1px solid ${C.borderLight}` : 'none',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                {/* Plain avatar: navy border, navy initial, white bg */}
                <div style={{
                  width: 40, height: 40, borderRadius: '50%',
                  border: `1px solid ${C.navy}`, background: C.white,
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: '14px', fontWeight: 500, color: C.navy,
                }}>
                  {driver.name.charAt(0)}
                </div>
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <p style={{ fontSize: '14px', fontWeight: 500, color: C.navy }}>{driver.name}</p>
                    {index === 0 && (
                      <span style={{
                        borderRadius: 9999, border: `1px solid ${C.navy}`,
                        padding: '2px 8px', fontSize: '10px', fontWeight: 500,
                        color: C.navy, background: 'transparent',
                      }}>TOP</span>
                    )}
                  </div>
                  <p style={{ fontSize: '12px', color: C.muted }}>{driver.vehiclePlate} · {driver.totalTrips} trips</p>
                </div>
              </div>
              <div style={{ textAlign: 'right' }}>
                <div style={{ borderBottom: `2px solid ${C.orange}`, display: 'inline-block', paddingBottom: 2 }}>
                  <span style={{ fontSize: '18px', fontWeight: 500, color: C.navy }}>{driver.safetyScore}</span>
                </div>
                <p style={{ fontSize: '12px', fontWeight: 400, color: trend.color, marginTop: 4 }}>
                  {trend.label} {trend.icon} this week
                </p>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

/* ── Section 4: Needs Attention ── */

function NeedsAttention({ drivers }) {
  const bottom3 = [...drivers].sort((a, b) => a.safetyScore - b.safetyScore).slice(0, 3);

  return (
    <div style={{ borderRadius: 12, border: `1px solid ${C.border}`, background: C.white }}>
      <div style={{ borderBottom: `1px solid ${C.border}`, padding: '20px 24px' }}>
        <p style={sectionHeadingStyle}>Needs Attention</p>
      </div>
      <div style={{ padding: '12px 16px' }}>
        {bottom3.map((driver, index) => {
          const trend = trendArrow(driver.scoreTrend);
          const label = scoreLabel(driver.safetyScore);
          return (
            <div
              key={driver.id}
              style={{
                display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16,
                padding: '16px 8px',
                borderLeft: `3px solid ${C.orange}`,
                marginBottom: index < bottom3.length - 1 ? 8 : 0,
                borderBottom: index < bottom3.length - 1 ? `1px solid ${C.borderLight}` : 'none',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                {/* Plain avatar */}
                <div style={{
                  width: 40, height: 40, borderRadius: '50%',
                  border: `1px solid ${C.navy}`, background: C.white,
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: '14px', fontWeight: 500, color: C.navy,
                }}>
                  {driver.name.charAt(0)}
                </div>
                <div>
                  <p style={{ fontSize: '14px', fontWeight: 500, color: C.navy }}>{driver.name}</p>
                  <p style={{ fontSize: '12px', color: C.muted }}>{driver.vehiclePlate} · {driver.totalTrips} trips</p>
                  {driver.mainIssue && (
                    <span style={{
                      marginTop: 4, display: 'inline-block',
                      borderRadius: 9999, border: `1px solid ${C.navy}`,
                      padding: '2px 8px', fontSize: '10px', fontWeight: 500,
                      color: C.navy, background: 'transparent',
                    }}>
                      {driver.mainIssue}
                    </span>
                  )}
                </div>
              </div>
              <div style={{ textAlign: 'right' }}>
                <div style={{ display: 'flex', alignItems: 'baseline', gap: 6, justifyContent: 'flex-end' }}>
                  <span style={{ fontSize: '18px', fontWeight: 500, color: C.navy }}>{driver.safetyScore}</span>
                  <span style={{ fontSize: '11px', fontWeight: 400, color: C.muted }}>{label}</span>
                </div>
                <p style={{ fontSize: '12px', fontWeight: 400, color: trend.color, marginTop: 4 }}>
                  {trend.label} {trend.icon} this week
                </p>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

/* ── Section 5: All Drivers Table ── */

const TABLE_COLUMNS = [
  { key: 'name', label: 'Driver' },
  { key: 'vehiclePlate', label: 'Vehicle' },
  { key: 'safetyScore', label: 'SAFAR Score' },
  { key: 'totalTrips', label: 'Trips' },
  { key: 'harshBraking', label: 'Harsh Braking' },
  { key: 'overspeeding', label: 'Overspeeding' },
  { key: 'swerving', label: 'Swerving' },
  { key: 'phoneUsage', label: 'Phone Usage' },
  { key: 'fatigue', label: 'Fatigue' },
  { key: 'scoreTrend', label: 'Trend' },
];

function DriversTable({ drivers }) {
  const [sortKey, setSortKey] = useState('safetyScore');
  const [sortAsc, setSortAsc] = useState(false);

  const sorted = useMemo(() => {
    const copy = [...drivers];
    copy.sort((a, b) => {
      const aVal = a[sortKey];
      const bVal = b[sortKey];
      if (typeof aVal === 'string') return sortAsc ? aVal.localeCompare(bVal) : bVal.localeCompare(aVal);
      return sortAsc ? aVal - bVal : bVal - aVal;
    });
    return copy;
  }, [drivers, sortKey, sortAsc]);

  const handleSort = (key) => {
    if (sortKey === key) {
      setSortAsc(!sortAsc);
    } else {
      setSortKey(key);
      setSortAsc(false);
    }
  };

  const thStyle = {
    cursor: 'pointer', whiteSpace: 'nowrap',
    padding: '12px 16px', fontSize: '11px', fontWeight: 500,
    textTransform: 'uppercase', letterSpacing: '0.08em',
    color: C.muted, transition: 'color 0.15s',
    borderBottom: `1px solid ${C.border}`,
    background: C.offWhite,
  };

  const tdStyle = {
    padding: '14px 16px', fontSize: '14px', fontWeight: 400,
    color: C.navy, whiteSpace: 'nowrap',
  };

  return (
    <div style={{ borderRadius: 12, border: `1px solid ${C.border}`, background: C.white }}>
      <div style={{ borderBottom: `1px solid ${C.border}`, padding: '20px 24px' }}>
        <p style={sectionHeadingStyle}>All Drivers</p>
        <p style={{ marginTop: 4, fontSize: '13px', color: C.muted, fontWeight: 400 }}>
          Click any column to sort. Click "View Details" for individual driver breakdown.
        </p>
      </div>
      <div className="overflow-x-auto">
        <table style={{ width: '100%', textAlign: 'left', borderCollapse: 'collapse' }}>
          <thead>
            <tr>
              {TABLE_COLUMNS.map((col) => (
                <th
                  key={col.key}
                  onClick={() => handleSort(col.key)}
                  style={thStyle}
                >
                  {col.label}
                  {sortKey === col.key && (
                    <span style={{ marginLeft: 4, color: C.orange }}>{sortAsc ? '\u2191' : '\u2193'}</span>
                  )}
                </th>
              ))}
              <th style={{ ...thStyle, cursor: 'default' }}>Action</th>
            </tr>
          </thead>
          <tbody>
            {sorted.map((driver) => {
              const label = scoreLabel(driver.safetyScore);
              const trend = trendArrow(driver.scoreTrend);
              return (
                <tr key={driver.id} style={{ borderBottom: `1px solid ${C.borderLight}`, transition: 'background 0.15s' }}
                  onMouseEnter={(e) => e.currentTarget.style.background = C.offWhite}
                  onMouseLeave={(e) => e.currentTarget.style.background = 'transparent'}
                >
                  {/* Driver */}
                  <td style={tdStyle}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                      <div style={{
                        width: 32, height: 32, borderRadius: '50%',
                        border: `1px solid ${C.navy}`, background: C.white,
                        display: 'flex', alignItems: 'center', justifyContent: 'center',
                        fontSize: '12px', fontWeight: 500, color: C.navy,
                      }}>
                        {driver.name.charAt(0)}
                      </div>
                      <span style={{ fontSize: '14px', fontWeight: 500, color: C.navy }}>{driver.name}</span>
                    </div>
                  </td>
                  {/* Vehicle */}
                  <td style={{ ...tdStyle, fontSize: '12px', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.06em', color: C.muted }}>
                    {driver.vehiclePlate}
                  </td>
                  {/* Score — navy number with muted label, orange bottom border */}
                  <td style={tdStyle}>
                    <span style={{
                      display: 'inline-block', borderBottom: `2px solid ${C.orange}`,
                      paddingBottom: 2, fontSize: '14px', fontWeight: 500, color: C.navy,
                    }}>
                      {driver.safetyScore}
                    </span>
                    <span style={{ marginLeft: 6, fontSize: '11px', fontWeight: 400, color: C.muted }}>
                      {label}
                    </span>
                  </td>
                  {/* Trips */}
                  <td style={tdStyle}>{driver.totalTrips}</td>
                  {/* Harsh Braking */}
                  <td style={tdStyle}>{driver.harshBraking}</td>
                  {/* Overspeeding */}
                  <td style={tdStyle}>{driver.overspeeding}</td>
                  {/* Swerving */}
                  <td style={tdStyle}>{driver.swerving}</td>
                  {/* Phone Usage */}
                  <td style={tdStyle}>{driver.phoneUsage}</td>
                  {/* Fatigue */}
                  <td style={tdStyle}>{driver.fatigue}</td>
                  {/* Trend — navy for positive, orange for negative */}
                  <td style={tdStyle}>
                    <span style={{ fontSize: '14px', fontWeight: 500, color: trend.color }}>
                      {trend.label} {trend.icon}
                    </span>
                  </td>
                  {/* Action */}
                  <td style={tdStyle}>
                    <Link
                      href={`/owner/reports/driver/${driver.id}`}
                      style={{
                        display: 'inline-flex', alignItems: 'center',
                        borderRadius: 8, border: `1px solid ${C.border}`,
                        padding: '6px 12px', fontSize: '12px', fontWeight: 500,
                        color: C.navy, textDecoration: 'none', transition: 'all 0.15s',
                      }}
                      onMouseEnter={(e) => { e.currentTarget.style.borderColor = C.orange; e.currentTarget.style.color = C.orange; }}
                      onMouseLeave={(e) => { e.currentTarget.style.borderColor = C.border; e.currentTarget.style.color = C.navy; }}
                    >
                      View Details
                    </Link>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

/* ── Section 6: Risk Event Breakdown ── */

function RiskEventBreakdown({ riskEvents, totalEvents }) {
  const maxCount = Math.max(...riskEvents.map((e) => e.count));

  return (
    <div style={{ borderRadius: 12, border: `1px solid ${C.border}`, background: C.white }}>
      <div style={{ borderBottom: `1px solid ${C.border}`, padding: '20px 24px' }}>
        <p style={sectionHeadingStyle}>Risk Events This Period</p>
        <p style={{ marginTop: 4, fontSize: '13px', color: C.muted, fontWeight: 400 }}>
          Breakdown of all safety events across the fleet.
        </p>
      </div>
      <div style={{ padding: '20px 24px', display: 'flex', flexDirection: 'column', gap: 16 }}>
        {riskEvents.map((event) => {
          const pct = maxCount > 0 ? (event.count / maxCount) * 100 : 0;
          return (
            <div key={event.type}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <p style={{ fontSize: '14px', fontWeight: 400, color: C.navy }}>{event.label}</p>
                <p style={{ fontSize: '14px', fontWeight: 500, color: C.navy }}>{event.count}</p>
              </div>
              {/* All bars: solid navy fill */}
              <div style={{ marginTop: 8, height: 10, width: '100%', borderRadius: 9999, background: C.borderLight, overflow: 'hidden' }}>
                <div
                  style={{
                    height: '100%', borderRadius: 9999,
                    background: C.navy,
                    width: `${pct}%`,
                    transition: 'width 0.7s ease',
                  }}
                />
              </div>
            </div>
          );
        })}
        <div style={{ borderTop: `1px solid ${C.border}`, paddingTop: 16 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <p style={{ fontSize: '14px', fontWeight: 500, color: C.navy }}>Total Events</p>
            <p style={{ fontSize: '20px', fontWeight: 500, color: C.navy }}>{totalEvents}</p>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ── Section 7: Score Distribution Chart (SVG) ── */

function ScoreDistributionChart({ distribution }) {
  const bars = [
    { label: 'Excellent', sublabel: '85-100', count: distribution.excellent },
    { label: 'Good', sublabel: '70-84', count: distribution.good },
    { label: 'Average', sublabel: '50-69', count: distribution.average },
    { label: 'High Risk', sublabel: '0-49', count: distribution.highRisk },
  ];

  const maxCount = Math.max(...bars.map((b) => b.count), 1);
  const barWidth = 60;
  const gap = 30;
  const chartWidth = bars.length * (barWidth + gap) - gap + 60;
  const chartHeight = 220;
  const maxBarHeight = 140;

  return (
    <div style={{ borderRadius: 12, border: `1px solid ${C.border}`, background: C.white }}>
      <div style={{ borderBottom: `1px solid ${C.border}`, padding: '20px 24px' }}>
        <p style={sectionHeadingStyle}>Driver Score Distribution</p>
        <p style={{ marginTop: 4, fontSize: '13px', color: C.muted, fontWeight: 400 }}>
          How many drivers fall into each safety band.
        </p>
      </div>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24 }}>
        <svg viewBox={`0 0 ${chartWidth} ${chartHeight}`} className="w-full max-w-md" role="img" aria-label="Score distribution bar chart">
          {bars.map((bar, i) => {
            const barHeight = maxCount > 0 ? (bar.count / maxCount) * maxBarHeight : 0;
            const x = 30 + i * (barWidth + gap);
            const y = chartHeight - 50 - barHeight;

            return (
              <g key={bar.label}>
                {/* All bars: solid navy */}
                <rect x={x} y={y} width={barWidth} height={barHeight} rx={6} fill={C.navy} opacity={0.85} />
                {/* Count label */}
                <text x={x + barWidth / 2} y={y - 8} textAnchor="middle" fill={C.navy} fontSize="14" fontWeight="500">{bar.count}</text>
                {/* Category label — plain gray */}
                <text x={x + barWidth / 2} y={chartHeight - 28} textAnchor="middle" fill={C.muted} fontSize="11" fontWeight="400">{bar.label}</text>
                {/* Score range */}
                <text x={x + barWidth / 2} y={chartHeight - 12} textAnchor="middle" fill="#9CA3AF" fontSize="10">{bar.sublabel}</text>
              </g>
            );
          })}
        </svg>
      </div>
    </div>
  );
}

/* ── Section 8: Weekly Trend Chart (SVG) ── */

function WeeklyTrendChart({ trendData }) {
  const chartWidth = 380;
  const chartHeight = 200;
  const padX = 50;
  const padY = 30;
  const plotW = chartWidth - padX * 2;
  const plotH = chartHeight - padY * 2;

  const scores = trendData.map((d) => d.avgScore);
  const minScore = Math.max(0, Math.min(...scores) - 10);
  const maxScore = Math.min(100, Math.max(...scores) + 10);
  const scoreRange = maxScore - minScore || 1;

  const points = trendData.map((d, i) => {
    const x = padX + (i / (trendData.length - 1)) * plotW;
    const y = padY + plotH - ((d.avgScore - minScore) / scoreRange) * plotH;
    return { x, y, ...d };
  });

  const linePath = points.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x} ${p.y}`).join(' ');
  const improving = scores[scores.length - 1] >= scores[0];

  return (
    <div style={{ borderRadius: 12, border: `1px solid ${C.border}`, background: C.white }}>
      <div style={{ borderBottom: `1px solid ${C.border}`, padding: '20px 24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <p style={sectionHeadingStyle}>Fleet Score Trend</p>
          {/* Trend badge — navy text for improving, orange for declining */}
          <span style={{
            borderRadius: 9999, border: `1px solid ${improving ? C.navy : C.orange}`,
            padding: '2px 8px', fontSize: '10px', fontWeight: 500,
            color: improving ? C.navy : C.orange, background: 'transparent',
          }}>
            {improving ? '\u2191 Improving' : '\u2193 Declining'}
          </span>
        </div>
        <p style={{ marginTop: 4, fontSize: '13px', color: C.muted, fontWeight: 400 }}>
          Fleet average SAFAR Score over the last 4 weeks.
        </p>
      </div>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24 }}>
        <svg viewBox={`0 0 ${chartWidth} ${chartHeight}`} className="w-full max-w-md" role="img" aria-label="Fleet score trend line chart">
          {/* Grid lines */}
          {[0, 1, 2, 3, 4].map((i) => {
            const y = padY + (i / 4) * plotH;
            const val = Math.round(maxScore - (i / 4) * scoreRange);
            return (
              <g key={i}>
                <line x1={padX} y1={y} x2={chartWidth - padX} y2={y} stroke={C.border} strokeWidth={1} />
                <text x={padX - 8} y={y + 4} textAnchor="end" fill="#9CA3AF" fontSize="10">{val}</text>
              </g>
            );
          })}

          {/* Gradient area — very light navy tint */}
          <defs>
            <linearGradient id="trendGrad" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stopColor={C.navy} stopOpacity="0.10" />
              <stop offset="100%" stopColor={C.navy} stopOpacity="0" />
            </linearGradient>
          </defs>
          <path
            d={`${linePath} L ${points[points.length - 1].x} ${padY + plotH} L ${points[0].x} ${padY + plotH} Z`}
            fill="url(#trendGrad)"
          />

          {/* Line — navy stroke */}
          <path d={linePath} fill="none" stroke={C.navy} strokeWidth={2.5} strokeLinecap="round" strokeLinejoin="round" />

          {/* Points and labels */}
          {points.map((p) => (
            <g key={p.week}>
              <circle cx={p.x} cy={p.y} r={5} fill={C.white} stroke={C.navy} strokeWidth={2.5} />
              <text x={p.x} y={p.y - 12} textAnchor="middle" fill={C.navy} fontSize="12" fontWeight="500">{p.avgScore}</text>
              <text x={p.x} y={padY + plotH + 16} textAnchor="middle" fill={C.muted} fontSize="10">{p.label}</text>
            </g>
          ))}
        </svg>
      </div>
    </div>
  );
}

/* ── Main Page ── */

export default function OwnerReportsPage() {
  const workspace = useOwnerWorkspaceData();
  const [dateFilter, setDateFilter] = useState('this_week');

  // Use dummy data for now — real API integration comes later
  const reportData = useMemo(() => getDummyReportData(), []);

  return (
    <OwnerShell section="reports" fleet={workspace.fleet} user={workspace.user} toast={workspace.toast}>
      {!workspace.isLoaded ? (
        <WorkspaceLoading />
      ) : workspace.fleetEnsureError ? (
        <WorkspaceError message={workspace.fleetEnsureError} onRetry={workspace.ensureFleetExists} />
      ) : workspace.isFleetSetupPending ? (
        <FleetSetupPanel
          fleetSetupName={workspace.fleetSetupName}
          setFleetSetupName={workspace.setFleetSetupName}
          onSubmit={workspace.handleCompleteFleetSetup}
          isSettingUpFleet={workspace.isSettingUpFleet}
        />
      ) : (
        <div className="space-y-6">
          {/* Section 1 — Top Bar */}
          <TopBar dateFilter={dateFilter} setDateFilter={setDateFilter} summary={reportData.summary} />

          {/* Section 2 — Fleet Summary Cards */}
          <SummaryCards summary={reportData.summary} />

          {/* Section 3 & 4 — Top Performers + Needs Attention */}
          <div className="grid gap-6 xl:grid-cols-2">
            <TopPerformers drivers={reportData.drivers} />
            <NeedsAttention drivers={reportData.drivers} />
          </div>

          {/* Section 5 — All Drivers Table */}
          <DriversTable drivers={reportData.drivers} />

          {/* Section 6 & 7 — Risk Events + Score Distribution */}
          <div className="grid gap-6 xl:grid-cols-2">
            <RiskEventBreakdown riskEvents={reportData.riskEvents} totalEvents={reportData.totalRiskEvents} />
            <ScoreDistributionChart distribution={reportData.scoreDistribution} />
          </div>

          {/* Section 8 — Weekly Trend */}
          <WeeklyTrendChart trendData={reportData.weeklyTrend} />
        </div>
      )}
    </OwnerShell>
  );
}
